Report error in console

diff --git a/.github/workflows/sanity-check.yml b/.github/workflows/sanity-check.yml
--- a/.github/workflows/sanity-check.yml
+++ b/.github/workflows/sanity-check.yml
@@ -22,6 +22,7 @@ jobs:
 
       - uses: actions/github-script@v3
         if: ${{ steps.sanity_check_pr_content.outcome == 'success'}}
+        continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
@@ -34,6 +35,7 @@ jobs:
 
       - uses: actions/github-script@v3
         if: ${{ steps.sanity_check_pr_content.outcome == 'failure'}}
+        continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
@@ -45,6 +47,18 @@ jobs:
             })
 
       - uses: actions/github-script@v3
+        if: ${{ always() && steps.sanity_check_pr_content.outcome == 'success'}}
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          script: |
+            github.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: '👋 Thanks for the PR!  The sanity check has been a success. Please wait for the test result.'
+            })
+
+      - uses: actions/github-script@v3
         if: ${{ always() && steps.sanity_check_pr_content.outcome == 'failure'}}
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
@@ -53,5 +67,11 @@ jobs:
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: '👋 Thanks for the PR!  The sanity check has been failed. Please ensure only chart related files have been modified.'
+              body: '👋 Thanks for the PR!  The sanity check has been a failure. Please ensure only chart related files have been modified.'
             })
+
+      - name: Reflect on Sanity Check PR Content
+        if: ${{ always() && steps.sanity_check_pr_content.outcome == 'failure'}}
+        run: |
+          echo "The 'Sanity Check PR Content' step has failed."
+          exit 1
